### ISSUE TITLE
build(lint): fix linter - doesn't work after last prettier upgrade to v3.0.0

### ISSUE THREAD

**Issue by outSH** [hyperledger/cacti#2727]
**Describe the bug**

`npm run lint` returns error after upgrade of prettier from 2.8.8 to 3.0.3. We must probably fix the eslint config or upgrade `eslint`/`eslint-plugin-prettier`  for compatibility.

As a side note, we could also run lint --fix on entire repo and commit the changes since a lot of a files are not formatted correctly and running the command locally adds a lot of changes (also deny commits that breaks the formatting from now on).

**Logs/Stack traces**

``` bash
vagrant@CactusDevVM:~/cactus$ npm run lint

> lint
> eslint '*/*/src/**/*.{js,ts}' --quiet --fix && cspell "*/*/src/**/*.{js,ts}"


Oops! Something went wrong! :(

ESLint: 7.32.0

TypeError: prettier.resolveConfig.sync is not a function
Occurred while linting /home/vagrant/cactus/examples/cactus-check-connection-ethereum-validator/src/test/typescript/integration/check-config-files.test.ts:1
    at Program (/home/vagrant/cactus/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:163:40)
    at /home/vagrant/cactus/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/vagrant/cactus/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/vagrant/cactus/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (/home/vagrant/cactus/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (/home/vagrant/cactus/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (/home/vagrant/cactus/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /home/vagrant/cactus/node_modules/eslint/lib/linter/linter.js:960:32
    at Array.forEach (<anonymous>)

Oops! Something went wrong! :(

ESLint: 7.32.0

TypeError: Invalid host defined options
    at Object.<anonymous> (/home/vagrant/cactus/node_modules/prettier/index.cjs:600:23)
    at Module._compile (/home/vagrant/cactus/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (/home/vagrant/cactus/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Program (/home/vagrant/cactus/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:157:26)
    at /home/vagrant/cactus/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
```

**Comment by petermetz** [comment]
@outSH Thank you for reporting!

Note to self: I found this on the internet as the likely fix:

    There is an incompatibility between prettier 3 and eslint-plugin-prettier 4.
    
    You can fix this by using version 5 of eslint-plugin-prettier:
    
    yarn add -D eslint-plugin-prettier@5.0.0
    
    or
    
    npm install --save-dev eslint-plugin-prettier@5.0.0
    
        Official issue: https://github.com/prettier/eslint-plugin-prettier/issues/562
        v5 release notes: https://github.com/prettier/eslint-plugin-prettier/releases/tag/v5.0.0
    
Source: https://stackoverflow.com/a/76625797

**Comment by petermetz** [comment]
> As a side note, we could also run lint --fix on entire repo and commit the changes

@outSH I got it right here, but it needs review from the other maintainers (:
https://github.com/hyperledger/cacti/pull/2713
