### PR TITLE
build(lint): fix linter - doesn't work after last prettier upgrade to v3.0.0

### LINKED ISSUE #2727: build(lint): fix linter - doesn't work after last prettier upgrade to v3.0.0
**Describe the bug**

`npm run lint` returns error after upgrade of prettier from 2.8.8 to 3.0.3. We must probably fix the eslint config or upgrade `eslint`/`eslint-plugin-prettier`  for compatibility.

As a side note, we could also run lint --fix on entire repo and commit the changes since a lot of a files are not formatted correctly and running the command locally adds a lot of changes (also deny commits that breaks the formatting from now on).

**Logs/Stack traces**

``` bash
vagrant@CactusDevVM:~/cactus$ npm run lint

> lint
> eslint '*/*/src/**/*.{js,ts}' --quiet --fix && cspell "*/*/src/**/*.{js,ts}"


Oops! Something went wrong! :(

ESLint: 7.32.0

TypeError: prettier.resolveConfig.sync is not a function
Occurred while linting /home/vagrant/cactus/examples/cactus-check-connection-ethereum-validator/src/test/typescript/integration/check-config-files.test.ts:1
    at Program (/home/vagrant/cactus/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:163:40)
    at /home/vagrant/cactus/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/vagrant/cactus/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/vagrant/cactus/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (/home/vagrant/cactus/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (/home/vagrant/cactus/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (/home/vagrant/cactus/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /home/vagrant/cactus/node_modules/eslint/lib/linter/linter.js:960:32
    at Array.forEach (<anonymous>)

Oops! Something went wrong! :(

ESLint: 7.32.0

TypeError: Invalid host defined options
    at Object.<anonymous> (/home/vagrant/cactus/node_modules/prettier/index.cjs:600:23)
    at Module._compile (/home/vagrant/cactus/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (/home/vagrant/cactus/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Program (/home/vagrant/cactus/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:157:26)
    at /home/vagrant/cactus/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
```

### PR DESCRIPTION
**Pull request by petermetz**
I ran `yarn up eslint-plugin-prettier --exact` to produce the diff of
this commit. I also ran `yarn lint` to verify that the linter works.

[skip ci]

Fixes #2727

Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>

**Pull Request Requirements**
[x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
[x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
[x] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information.

**Character Limit**
[x] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
[x] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM

**Comment by jagpreetsinghsasan** [comment]
@petermetz I think this PR will fix my CI errors as well (facing this while running the configure script from git action)
image

**Comment by petermetz** [comment]
> @petermetz I think this PR will fix my CI errors as well (facing this while running the configure script from git action) image

@jagpreetsinghsasan Fingers crossed! Does this reproduce on the main branch as well? (the errors you just posted in the screenshot)

**Review by izuru0 — APPROVED** [review]
LGTM
