### ISSUE TITLE
fix(relay): rust build fails after tokio bump from 0.2.25 to 1.18.5

### ISSUE THREAD

**Issue by sandeepnRES** [hyperledger/cacti#2349]
**Describe the bug**

Since the update of tokio version to 1.x, the build of relay is failing.

**To Reproduce**

Go to `weaver/core/relay` and run `make build-local`.

**Expected behavior**

Build should succeed.

**Logs/Stack traces**

```
   Compiling relay v1.5.4 (/opt/relay)
error: The #[tokio::main] macro requires rt or rt-multi-thread.
 --> src/client_tls.rs:8:1
  |
8 | #[tokio::main]
  | ^^^^^^^^^^^^^^
  |
  = note: this error originates in the attribute macro `tokio::main` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unused imports: `NetworkQuery`, `network_client::NetworkClient`
 --> src/client_tls.rs:2:36
  |
2 | use weaverpb::networks::networks::{network_client::NetworkClient, NetworkQuery};
  |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `std::net::SocketAddr`
  --> driver/driver.rs:14:5
   |
14 | use std::net::SocketAddr;
   |     ^^^^^^^^^^^^^^^^^^^^

warning: unused import: `std::net::ToSocketAddrs`
  --> driver/driver.rs:15:5
   |
15 | use std::net::ToSocketAddrs;
   |     ^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `tonic::transport::Server`
  --> driver/driver.rs:19:5
   |
19 | use tonic::transport::Server;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0601]: `main` function not found in crate `dummy_driver`
   --> driver/driver.rs:246:2
    |
246 | }
    |  ^ consider adding a `main` function to `driver/driver.rs`

Some errors have detailed explanations: E0425, E0432, E0601, E0603.
For more information about an error, try `rustc --explain E0425`.
warning: `relay` (bin "dummy-driver") generated 5 warnings
error: could not compile `relay` due to 6 previous errors; 5 warnings emitted
The command '/bin/sh -c cd /opt/relay && RUSTFLAGS="-Clinker=musl-gcc -Crelocation-model=static" cargo build --release --target x86_64-unknown-linux-musl' returned a non-zero code: 101
make: *** [Makefile:90: build-server-local] Error 101
```

@petermetz Since you are familiar with Rust, please let us know if you could provide any insight on how we can update the codebase to adapt to newer tokio version.

**Comment by petermetz** [comment]
@sandeepnRES FYI: I updated the issue title a bit to make it more unique (the build will start failing many more times so just saying that it does will produce a lot of issues and commit subjects that will look like they are the same)
